name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake -G Ninja .
    - name: ninja
      run: ninja
    - name: test
      run: mkdir db; cd db; ../bin/ib_test5
    
