name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: cmake
  #     run: cmake -G "Unix Makefiles" .
  #   - name: make
  #     run: make
  build-linux:
    runs-on: ubuntu-latest
    container: gcc:13
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Install CMake
        run: |
          apt update -y
          apt install -y cmake
        shell: bash
      - name: liburing
        run: git config --global --add safe.directory /__w/embedded-innodb/embedded-innodb && git submodule update --init --recursive
      - name: cmake
        run: cmake -G "Unix Makefiles" .
      - name: make
        run: make
      
